// Mocks generated by Mockito 5.4.6 from annotations
// in social_destiny/test/unit/post_repositorie_test/post_repositorie_remote_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:social_destiny/data/services/app_gateway.dart' as _i2;
import 'package:social_destiny/data/services/models/post_api.dart' as _i6;
import 'package:social_destiny/utils/result.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePosts_0 extends _i1.SmartFake implements _i2.Posts {
  _FakePosts_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppGateway].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppGateway extends _i1.Mock implements _i2.AppGateway {
  MockAppGateway() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Posts get postsGateway =>
      (super.noSuchMethod(
            Invocation.getter(#postsGateway),
            returnValue: _FakePosts_0(this, Invocation.getter(#postsGateway)),
          )
          as _i2.Posts);
}

/// A class which mocks [Posts].
///
/// See the documentation for Mockito's code generation for more information.
class MockPosts extends _i1.Mock implements _i2.Posts {
  MockPosts() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get url =>
      (super.noSuchMethod(
            Invocation.getter(#url),
            returnValue: _i3.dummyValue<String>(this, Invocation.getter(#url)),
          )
          as String);

  @override
  _i4.Future<_i5.Result<List<_i6.PostApi>>> getPosts() =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, []),
            returnValue: _i4.Future<_i5.Result<List<_i6.PostApi>>>.value(
              _i3.dummyValue<_i5.Result<List<_i6.PostApi>>>(
                this,
                Invocation.method(#getPosts, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<List<_i6.PostApi>>>);

  @override
  _i4.Future<_i5.Result<_i6.PostApi>> getPost(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPost, [id]),
            returnValue: _i4.Future<_i5.Result<_i6.PostApi>>.value(
              _i3.dummyValue<_i5.Result<_i6.PostApi>>(
                this,
                Invocation.method(#getPost, [id]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.PostApi>>);
}
